name: flutter_gen_runner

description: The Flutter code generator for your assets, fonts, colors, … — Get rid of all String-based APIs.
version: 5.2.0
homepage: https://github.com/FlutterGen/flutter_gen
repository: https://github.com/FlutterGen/flutter_gen
documentation: https://github.com/FlutterGen/flutter_gen
issue_tracker: https://github.com/FlutterGen/flutter_gen/issues

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
#  flutter_gen_core: 5.2.0
  flutter_gen_core:
    git:
      url: https://github.com/quest3/flutter_gen.git
      path: packages/core
      ref: 802a6c4bfa920524129255303d3d99fb73228069
  build: '>=2.0.0 <3.0.0'
  collection: '>=1.15.0 <2.0.0'
  crypto: '>=3.0.0 <4.0.0'
  glob: '>=2.0.0 <3.0.0'
  path: '>=1.8.0 <2.0.0'

dev_dependencies:
  flutter_lints: '>=2.0.1 <3.0.0'
  build_test: '>=2.0.0 <3.0.0'
